[[CURRENCIES]]
code = "TN"
issuer = "GBV7DATMFOK2DOR4RT6Y7S6TCKJJXA57TQHNWHPBXQ2MHNC3D36I2HSP"
name = "TechNews"
desc = "TechNews token on Pi Testnet."
image = "https://mediceberg.github.io/technews-token/.well-known/pi.toml"
